language: node_js
node_js:
  - '8'
notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_success: always
    on_failure: always
script:
- yarn run build
- yarn run lint
- yarn run test-coverage
- yarn run codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target-branch: gh-pages
  on:
    branch: master